name: github_search

description: "Search app for GitHub"

publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  hive_flutter: ^1.1.0
  http: ^0.13.6
  provider: ^6.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  solid_lints: ^0.0.19

flutter:
  uses-material-design: true

  assets:
    - assets/icons/Actions/left.png
    - assets/icons/Functional/Ban.png
    - assets/icons/Functional/Close.png
    - assets/icons/Functional/Favorite_active.png
    - assets/icons/Functional/Favorite_default.png
    - assets/icons/Functional/Search.png
  fonts:
    - family: Raleway
      fonts:
       - asset: fonts/Raleway-VariableFont-wght.ttf
    
